import { Cormorant } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

const inter = Cormorant({
	subsets: ['cyrillic'],
	display: 'swap',
	weight: '700',
});

export const metadata = {
	title: 'Prisma test app',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html
			lang='en'
			data-theme='cupcake'
		>
			<body className={inter.className}>
				{' '}
				<Navbar></Navbar>
				{children}
				<Footer></Footer>
			</body>
		</html>
	);
}
